name: Destroy Infrastructure

on: 
  workflow_dispatch:

jobs:
  destroy_infra:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Terraform Init and Destroy
      run: |
        cd infra-lambda/
        terraform init
        terraform destroy -auto-approve
